version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - echo Running tests
      - npm install
      - yum install curl
      - curl
      - curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
      - sudo yum install nodejs

  build:
    commands:
      - echo Building for production
      - rm -rf node_modules
      - npm install --production
      - npm test

artifacts:
  files:
    - "**/*"
  name: MyMegaApp-$(date +%Y-%m-%d) 